[workspace]
members = ["client", "integration-tests", "server"]

[patch.'https://github.com/KZen-networks/multi-party-ecdsa']
multi-party-ecdsa = { git = "https://github.com/commerceblock/multi-party-ecdsa" }
