# DB options can be added here
db = "local"

region = "" # Override with ENV variable!
pool_id = "" # Override with ENV variable!
issuer = "" # Override with ENV variable!
audience = "" # Override with ENV variable!
