electrum_server = "127.0.0.1:60401"
network = "regtest"
required_confirmation = 0
testing_mode = false
lockheight_init = 10000
lh_decrement = 10

# Fees
fee_address = "bcrt1qjuwxs60ej7dp4sq9pswhqp7nwmcsng4p8x44mz,bcrt1qjuwxs60ej7dp4sq9pswhqp7nwmcsng4p8x44mz"
fee_deposit = 0
fee_withdraw = 300

# Swap parameters
punishment_duration = "300" # 1 hour
utxo_timeout = "60"
batch_lifetime = "600" # 1 hour

#Mainstay config
mainstay_config = ""

#Watch config
watch_only = false
bitcoind = ""
