electrum_server = "127.0.0.1:60401"
lockbox = ""
network = "regtest"
required_confirmation = 0
testing_mode = true
lockheight_init = 1000
lh_decrement = 10
# Fees
fee_address = "bcrt1qy6jn9a2lgaumeedqxzq2s0497s5zr5645xmzuk"
fee_deposit = 0
fee_withdraw = 50
# Swap parameters
punishment_duration = "3600" # 1 hour
utxo_timeout = "60"
batch_lifetime = "3600" # 1 hour
#Mainstay config
mainstay_config = ""
#Watch config
watch_only = false
bitcoind = ""
