
[package]
name = "shared"
version = "0.2.0"
authors = [
	"Lawrence Deacon <lawrence.deacon@gmail.com>",
  "Tomos Wootton <tomoswootton@protonmail.com"
]
edition = "2018"

[lib]
name = "shared_lib"
path = "src/lib.rs"

[dependencies]
hex = "0.3.2"
libsecp256k1 = "0.3.5"
bitcoin = { version = "0.20", features = [ "use-serde" ] }
rocket = { version = "0.4.2", default-features = false }
rocket_contrib = { version = "0.4.2", default-features = false,features = ["json"] }
rocksdb = "0.13.0"
uuid = { version = "0.7", features = ["v4"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rand = "0.6.5"
monotree = "0.1.3"
electrumx_client = { git = "https://github.com/commerceblock/rust-electrumx-client" }
reqwest = "0.9.5"
hyperx = "1.0.0"
hyper = "0.13.6"
itertools = "0.9.0"

[dependencies.curv]
git = "https://github.com/KZen-networks/curv"
tag = "v0.2.2"
features =  ["ec_secp256k1"]

[dependencies.kms]
git = "https://github.com/KZen-networks/kms-secp256k1"
tag = "v0.2.0"
