[package]
name = "tests"
version = "0.1.2"
authors = ["oleiba <oded@kzencorp.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
time-test = "0.2.1"
log = "0.4"
time = "*"
bitcoin = "0.20.0"

[dependencies.server]
path = "../server"

[dependencies.client]
path = "../client"

[dependencies.shared]
path = "../shared"
